name: Generate reports

description: Run tests and generate reports

runs:
  using: composite
  steps:
    - name: Run and report
      shell: bash
      run: |
        python -m pip install .[all]
        rm -rf .reports # Clean report directory
        pytest --junitxml=.reports/tests/tests.xml --html=.reports/tests/report.html \
            --cov-report xml:.reports/coverage/coverage.xml  \
            --cov-report html:.reports/coverage/report # Other options are handled by pyproject.toml
        genbadge tests -i .reports/tests/tests.xml -o images/test_badge.svg
        genbadge coverage -i .reports/coverage/coverage.xml -o images/coveragebadge.svg
        rm -rf .reports
