name: Generate Badges

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  reports:
    runs-on: ubuntu-latest
    name: Generate coverage and test reports
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[all]
    - name: Generate and push reports
      run: |
        rm -rf .reports # Clean report directory
        pytest --junitxml=.reports/tests/tests.xml --html=.reports/tests/report.html \
            --cov-report xml:.reports/coverage/coverage.xml  \
            --cov-report html:.reports/coverage/report # Other options are handled by pyproject.toml
        genbadge tests -i .reports/tests/tests.xml -o images/test_badge.svg
        genbadge coverage -i .reports/coverage/coverage.xml -o images/coveragebadge.svg
        rm -rf .reports
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add images/
        git commit -m "automatically generated badges"
        git push
